layout: post
title: Cameras Blog
author: Dragos Andreita
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"


# social links
twitter_username: Dragos Andreita # DO NOT include the @ character, or else the build will fail!
github_username:  Alidragos # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

minima:
    date_format: "%b %-d, %Y"
 
 social_links:
    twitter: jekyllrb
    github:  jekyll
    
 # Build settings
theme: minima
